# Generated by Django 5.0.4 on 2024-06-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Novelwrite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writing',
            old_name='content',
            new_name='blurb',
        ),
        migrations.AlterField(
            model_name='writing',
            name='title',
            field=models.CharField(default='Use Camel Case Only', max_length=200),
        ),
    ]
